export const SET_AUTH_DATA = "SET_AUTH_DATA";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";

export const SET_LOGIN_DATA = "SET_LOGIN_DATA";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_LOGIN_LOADING = "SET_LOGIN_LOADING";

export const SET_EMPLOYEE_DATA = "SET_EMPLOYEE_DATA";
export const SET_EMPLOYEE_ERROR = "SET_EMPLOYEE_ERROR";
export const SET_EMPLOYEE_LOADING_MORE = "SET_EMPLOYEE_LOADING_MORE";
export const SET_EMPLOYEE_LOADING = "SET_EMPLOYEE_LOADING";
